[package]
name = "near-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.23"
lru = "0.7.0"
rand = "0.7"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "cache"
harness = false

